name = "fpz"
prefix = "fpz"
author = "FP Mod Team"
modname = "fpz"
# keyname = "fpz_v{{version}}"
# signame = "fpz_v{{version}}"
reuse_private_key = false

[version]
major = 3
minor = 0
patch = 0

[files]
include = [
    "mod.cpp",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ca.paa",
    "README.md"
]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]